import Link from 'next/link'

export const metadata = { title: 'Terms of Service | Candid.ai' }

export default function TermsPage() {
  const lastUpdated = 'March 27, 2025'

  return (
    <div className="min-h-screen bg-[#0F1117] text-white">
      {/* Simple nav */}
      <nav className="border-b border-white/6 h-14 flex items-center px-6">
        <Link href="/" className="text-base font-bold gradient-text">
          Candid.ai
        </Link>
      </nav>

      <main className="max-w-2xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {lastUpdated}</p>

        <div className="space-y-8 text-sm text-slate-400 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-white mb-3">1. Acceptance</h2>
            <p>By creating an account or using Candid.ai, you agree to these terms. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">2. What Candid.ai is</h2>
            <p>Candid.ai is an AI-powered toolkit for recruiters. It uses Anthropic's Claude API to score resumes, generate candidate summaries, build Boolean search strings, and rank candidate shortlists. Results are generated by AI and should be reviewed by a human before acting on them. We do not guarantee the accuracy of any AI-generated output.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">3. Your account</h2>
            <p>You are responsible for keeping your login credentials secure. You may not share your account with others. Agency plan team seats must each use their own account. If you are the owner of an Agency account, you are responsible for the activity of your team members.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">4. Acceptable use</h2>
            <p>You may not use Candid.ai to process data you are not authorized to handle, to attempt to circumvent AI call limits, to reverse-engineer or scrape the service, or for any illegal purpose. Resume and job description text you submit must not include protected class information that would be illegal to use in a hiring decision.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">5. Subscriptions and billing</h2>
            <p>Free accounts include 25 AI calls per calendar month at no cost. Pro and Agency subscriptions are billed monthly via Square. Upgrading takes effect immediately. Cancellations take effect at the end of the current billing period — you retain access until then. If a payment fails, you have a 3-day grace period to update your billing before the account reverts to the Free tier.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">6. Refunds</h2>
            <p>We do not offer refunds on subscription charges. If you believe a charge was made in error, email us at <a href="mailto:billing@candidai.app" className="text-indigo-400 hover:text-indigo-300 transition-colors">billing@candidai.app</a> within 7 days and we will review it.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">7. Limitation of liability</h2>
            <p>Candid.ai is provided as-is. We are not liable for hiring decisions, placement outcomes, or any losses resulting from use of AI-generated output. Our total liability for any claim is limited to the amount you paid us in the 3 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">8. Termination</h2>
            <p>We may suspend or terminate your account if you violate these terms. You may cancel your account at any time from the billing settings page.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">9. Changes to these terms</h2>
            <p>We may update these terms. Continued use of the service after changes constitutes acceptance. Material changes will be communicated by email.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">10. Contact</h2>
            <p>Questions about these terms? Email <a href="mailto:legal@candidai.app" className="text-indigo-400 hover:text-indigo-300 transition-colors">legal@candidai.app</a>.</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-white/6">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-300 transition-colors">
            &larr; Back to Candid.ai
          </Link>
        </div>
      </main>
    </div>
  )
}
